// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: engine.proto

package engineGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_buy  Side = 0
	Side_sell Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "buy",
		1: "sell",
	}
	Side_value = map[string]int32{
		"buy":  0,
		"sell": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type CountOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CountOutput) Reset() {
	*x = CountOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOutput) ProtoMessage() {}

func (x *CountOutput) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOutput.ProtoReflect.Descriptor instead.
func (*CountOutput) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CountOutput) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DelistInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *DelistInput) Reset() {
	*x = DelistInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelistInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelistInput) ProtoMessage() {}

func (x *DelistInput) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelistInput.ProtoReflect.Descriptor instead.
func (*DelistInput) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *DelistInput) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type DelistOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *DelistOutput) Reset() {
	*x = DelistOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelistOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelistOutput) ProtoMessage() {}

func (x *DelistOutput) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelistOutput.ProtoReflect.Descriptor instead.
func (*DelistOutput) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *DelistOutput) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   Side   `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=Side" json:"Type,omitempty"`
	ID     string `protobuf:"bytes,2,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Amount string `protobuf:"bytes,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price  string `protobuf:"bytes,4,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	Pair   string `protobuf:"bytes,5,opt,name=Pair,json=pair,proto3" json:"Pair,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetType() Side {
	if x != nil {
		return x.Type
	}
	return Side_buy
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type OutputOrders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdersProcessed string `protobuf:"bytes,1,opt,name=OrdersProcessed,json=orders_processed,proto3" json:"OrdersProcessed,omitempty"`
	PartialOrder    string `protobuf:"bytes,2,opt,name=PartialOrder,json=partial_order,proto3" json:"PartialOrder,omitempty"`
}

func (x *OutputOrders) Reset() {
	*x = OutputOrders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputOrders) ProtoMessage() {}

func (x *OutputOrders) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputOrders.ProtoReflect.Descriptor instead.
func (*OutputOrders) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *OutputOrders) GetOrdersProcessed() string {
	if x != nil {
		return x.OrdersProcessed
	}
	return ""
}

func (x *OutputOrders) GetPartialOrder() string {
	if x != nil {
		return x.PartialOrder
	}
	return ""
}

type BookInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair  string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Limit int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *BookInput) Reset() {
	*x = BookInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInput) ProtoMessage() {}

func (x *BookInput) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInput.ProtoReflect.Descriptor instead.
func (*BookInput) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *BookInput) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *BookInput) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BookArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PriceAmount []string `protobuf:"bytes,1,rep,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
}

func (x *BookArray) Reset() {
	*x = BookArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookArray) ProtoMessage() {}

func (x *BookArray) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookArray.ProtoReflect.Descriptor instead.
func (*BookArray) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *BookArray) GetPriceAmount() []string {
	if x != nil {
		return x.PriceAmount
	}
	return nil
}

type BookOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buys  []*BookArray `protobuf:"bytes,1,rep,name=Buys,proto3" json:"Buys,omitempty"`
	Sells []*BookArray `protobuf:"bytes,2,rep,name=Sells,proto3" json:"Sells,omitempty"`
}

func (x *BookOutput) Reset() {
	*x = BookOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookOutput) ProtoMessage() {}

func (x *BookOutput) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookOutput.ProtoReflect.Descriptor instead.
func (*BookOutput) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *BookOutput) GetBuys() []*BookArray {
	if x != nil {
		return x.Buys
	}
	return nil
}

func (x *BookOutput) GetSells() []*BookArray {
	if x != nil {
		return x.Sells
	}
	return nil
}

var File_engine_proto protoreflect.FileDescriptor

var file_engine_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22,
	0x2e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x1e, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22,
	0x74, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x5e, 0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x12, 0x23, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x2e, 0x0a, 0x09,
	0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x0a,
	0x42, 0x6f, 0x6f, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x42, 0x75,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x52, 0x04, 0x42, 0x75, 0x79, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x53, 0x65,
	0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x05, 0x53, 0x65, 0x6c, 0x6c, 0x73, 0x2a, 0x19, 0x0a, 0x04,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x73, 0x65, 0x6c, 0x6c, 0x10, 0x01, 0x32, 0xe8, 0x01, 0x0a, 0x06, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x12, 0x20, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x06, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x0d, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x06, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x0d, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x06,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x06, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x06,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x0a, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x0b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x69, 0x72, 0x12, 0x0c, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x1a, 0x0d, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x47, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData = file_engine_proto_rawDesc
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_proto_rawDescData)
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_engine_proto_goTypes = []interface{}{
	(Side)(0),            // 0: Side
	(*Empty)(nil),        // 1: Empty
	(*CountOutput)(nil),  // 2: CountOutput
	(*DelistInput)(nil),  // 3: DelistInput
	(*DelistOutput)(nil), // 4: DelistOutput
	(*Order)(nil),        // 5: Order
	(*OutputOrders)(nil), // 6: OutputOrders
	(*BookInput)(nil),    // 7: BookInput
	(*BookArray)(nil),    // 8: BookArray
	(*BookOutput)(nil),   // 9: BookOutput
}
var file_engine_proto_depIdxs = []int32{
	5,  // 0: DelistOutput.orders:type_name -> Order
	0,  // 1: Order.Type:type_name -> Side
	8,  // 2: BookOutput.Buys:type_name -> BookArray
	8,  // 3: BookOutput.Sells:type_name -> BookArray
	5,  // 4: Engine.Process:input_type -> Order
	5,  // 5: Engine.ProcessMarket:input_type -> Order
	5,  // 6: Engine.Cancel:input_type -> Order
	7,  // 7: Engine.FetchBook:input_type -> BookInput
	1,  // 8: Engine.GetOrderBookCount:input_type -> Empty
	3,  // 9: Engine.DelistPair:input_type -> DelistInput
	6,  // 10: Engine.Process:output_type -> OutputOrders
	6,  // 11: Engine.ProcessMarket:output_type -> OutputOrders
	5,  // 12: Engine.Cancel:output_type -> Order
	9,  // 13: Engine.FetchBook:output_type -> BookOutput
	2,  // 14: Engine.GetOrderBookCount:output_type -> CountOutput
	4,  // 15: Engine.DelistPair:output_type -> DelistOutput
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelistInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelistOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputOrders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		EnumInfos:         file_engine_proto_enumTypes,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_rawDesc = nil
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EngineClient interface {
	Process(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error)
	ProcessMarket(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error)
	Cancel(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	FetchBook(ctx context.Context, in *BookInput, opts ...grpc.CallOption) (*BookOutput, error)
	GetOrderBookCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CountOutput, error)
	DelistPair(ctx context.Context, in *DelistInput, opts ...grpc.CallOption) (*DelistOutput, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Process(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error) {
	out := new(OutputOrders)
	err := c.cc.Invoke(ctx, "/Engine/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) ProcessMarket(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error) {
	out := new(OutputOrders)
	err := c.cc.Invoke(ctx, "/Engine/ProcessMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Cancel(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/Engine/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) FetchBook(ctx context.Context, in *BookInput, opts ...grpc.CallOption) (*BookOutput, error) {
	out := new(BookOutput)
	err := c.cc.Invoke(ctx, "/Engine/FetchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) GetOrderBookCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CountOutput, error) {
	out := new(CountOutput)
	err := c.cc.Invoke(ctx, "/Engine/GetOrderBookCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) DelistPair(ctx context.Context, in *DelistInput, opts ...grpc.CallOption) (*DelistOutput, error) {
	out := new(DelistOutput)
	err := c.cc.Invoke(ctx, "/Engine/DelistPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServer is the server API for Engine service.
type EngineServer interface {
	Process(context.Context, *Order) (*OutputOrders, error)
	ProcessMarket(context.Context, *Order) (*OutputOrders, error)
	Cancel(context.Context, *Order) (*Order, error)
	FetchBook(context.Context, *BookInput) (*BookOutput, error)
	GetOrderBookCount(context.Context, *Empty) (*CountOutput, error)
	DelistPair(context.Context, *DelistInput) (*DelistOutput, error)
}

// UnimplementedEngineServer can be embedded to have forward compatible implementations.
type UnimplementedEngineServer struct {
}

func (*UnimplementedEngineServer) Process(context.Context, *Order) (*OutputOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (*UnimplementedEngineServer) ProcessMarket(context.Context, *Order) (*OutputOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarket not implemented")
}
func (*UnimplementedEngineServer) Cancel(context.Context, *Order) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (*UnimplementedEngineServer) FetchBook(context.Context, *BookInput) (*BookOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBook not implemented")
}
func (*UnimplementedEngineServer) GetOrderBookCount(context.Context, *Empty) (*CountOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderBookCount not implemented")
}
func (*UnimplementedEngineServer) DelistPair(context.Context, *DelistInput) (*DelistOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelistPair not implemented")
}

func RegisterEngineServer(s *grpc.Server, srv EngineServer) {
	s.RegisterService(&_Engine_serviceDesc, srv)
}

func _Engine_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Process(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_ProcessMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).ProcessMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/ProcessMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).ProcessMarket(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Cancel(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_FetchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).FetchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/FetchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).FetchBook(ctx, req.(*BookInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_GetOrderBookCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).GetOrderBookCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/GetOrderBookCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).GetOrderBookCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_DelistPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelistInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).DelistPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/DelistPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).DelistPair(ctx, req.(*DelistInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Engine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Engine_Process_Handler,
		},
		{
			MethodName: "ProcessMarket",
			Handler:    _Engine_ProcessMarket_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Engine_Cancel_Handler,
		},
		{
			MethodName: "FetchBook",
			Handler:    _Engine_FetchBook_Handler,
		},
		{
			MethodName: "GetOrderBookCount",
			Handler:    _Engine_GetOrderBookCount_Handler,
		},
		{
			MethodName: "DelistPair",
			Handler:    _Engine_DelistPair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
